# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 498b3faa8153f7455a5b297490b6e11f77f4ee992e3d9e25497b86484955a37dfaf7c0e8295acbaa16f28da7987d0c46f959b1ac00949b1c4171ad6499fee3d4

test:
  secret_key_base: 58c918691926cfdf2cc9455fdb154bd83c08a99d97d481d43043d2d25f256652c439fe56e43ed3c1d8fb78866431535c2068d068dc92694f9cc3bb65141d4a9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
